### ISSUE TITLE
UI Delay

### ISSUE THREAD

**Issue by Mark-Joy** [DerGoogler/MMRL#40]
Is it just me or the UI kind of delay around 0.5-1 second every time I click something?

**Comment by YOEL-44** [comment]
I have a Xiaomi Mi Max 3 (6GB) with MatrixX ROM (A13).
This is most notable in the app settings, where I could be waiting for up to 5 seconds until a toggle visually gets enabled or disabled, this could be because of the blur effect.
The rest of the app is also kinda laggy but bearable, no matter how much I wait for it to settle there's always a kind of delay.

**Comment by DerGoogler** [comment]
This is caused by the settings system. I'm currently reworking that
